### ISSUE TITLE
Implement support for an Elasticsearch backend instead of in-browser Minimongo

### ISSUE THREAD

**Issue by Fgerthoffert** [zencrepes/zencrepes#103]
Current progress (first draft)
- [x] Github Issues
- [x] Github Pull Requests
- [x] Github Repositories
- [x] Github Labels
- [x] Github Milestones
- [x] Github Projects
- [x] Github Releases
- [x] Github Vulneratbilities
- [x] Github Watchers & Stargazers
- [x] Jira Issues
- [x] Circleci Pipelines
- [x] Circleci Environment Variables
- [x] Circleci Insights

**Comment by Fgerthoffert** [comment]
A first version of the indexer is done, now is just a matter of hooking the UI to the data. https://github.com/zencrepes/github-indexer

**Comment by marnovo** [comment]
Hi @Fgerthoffert, is there any update on this?

**Comment by Fgerthoffert** [comment]
Nothing concrete yet, lack of time atm.

**Comment by Fgerthoffert** [comment]
Finally able to make some progress on that front.

It's probably going to take a few weeks until the first release, but the indexer is in place, a basic GraphQL API (with an Elasticsearch backend), and the beginning of the PullRequests page and facets.

<img width="734" alt="Screen Shot 2020-03-30 at 10 31 38 PM" src="https://user-images.githubusercontent.com/5667028/77980801-3d958b80-72d6-11ea-9046-707d49130b91.png">

Now it's mostly a matter of porting everything to the new codebase.

**Comment by marnovo** [comment]
That's great news! Looking forward to it. Let me know at later stages if I can help with testing or so.

**Comment by Fgerthoffert** [comment]
Thanks @marnovo, any help is appreciated :)

I hope to have a docker-compose file ready in a week or so (only with Github PRs for now), then I'll port over the other entities (which should be pretty quick).

Current status (for PRs):
 - [x] Indexer
 - [x] Table view
 - [x] Term facets
 - [x] Metrics facets
 - [ ] Dates facets
 - [x] Query management (save query, open previously saved, clear)
 - [ ] Explore view & charts
 - [ ] Web hooks (to only use the indexer once, then receive changes from GitHub)

<img width="1913" alt="Screen Shot 2020-04-07 at 10 30 02 PM" src="https://user-images.githubusercontent.com/5667028/78738371-b7a1c200-791f-11ea-9164-ab0d5075851c.png">

**Comment by Fgerthoffert** [comment]
It's very rough, but I just wrapped up the very first round of integration and pushed a docker-compose file.

@marnovo If curious to try it out (only Pull Requests currently), instructions are available here: http://docs.zencrepes.io/ in the section "Try it!". The other sections of the documentation are not "ready" yet, even though some content is there.

**Comment by marnovo** [comment]
Thanks, will check it out!

**Comment by Fgerthoffert** [comment]
Finally, after months, things are taking shape and I'm going to be closing this issue.
