### ISSUE TITLE
Ability to pull in ZenHub story points

### ISSUE THREAD

**Issue by cvbrent** [zencrepes/zencrepes#123]
Hi there - I love ZenCrepes! Wondering if it would be possible to add functionality for those using ZenHub to pull in those story point values?

**Comment by Fgerthoffert** [comment]
I built something like this (some remanents are still there: https://github.com/zencrepes/zencrepes/blob/master/imports/ui/data/FetchZenhubPoints.js & https://github.com/zencrepes/zencrepes/blob/master/imports/ui/views/Settings/ImportPoints/Zenhub.js) but ended up removing the feature as I thought it was not going to be that useful (and it's fairly slow).

Technically it would just be a matter of cleaning up the code a bit and finding a new home for the view. If you want to take on to submit a PR, I'm happy to review.
