### ISSUE TITLE
zencrepes.io login oAuth button disabled

### ISSUE THREAD

**Issue by marnovo** [zencrepes/zencrepes#126]
I wanted to try ZenCrepes via zencrepes.io, however while the org has been requested/authorized correctly, when authorizing the profile login itself the green button "Authorize zencrepes" is disabled. Any idea of why or what may have happened? Thanks.

**Comment by Fgerthoffert** [comment]
Hi Marcelo,
That's weird, would you mind sending a screenshot ? do you see the green checkmark next to your org in the "Organization access" section ?

**Comment by marnovo** [comment]
@Fgerthoffert I believe it was cause by some partial GitHub outage that day! Thanks, closing this.
