### ISSUE TITLE
Add ability to exclude certain labels

### ISSUE THREAD

**Issue by alexsapran** [zencrepes/zencrepes#130]
When on the issues view I would like to be able to exclude certain labels that might not be related to what I am looking to find. 
Example use case:
- There is an issue with applied labels A.
- There is another issue just having the same label A for various other reasons alongside with label B.
- I want to find and plan for labels A and exclude any issues that also have label B. 

I managed to make that happen using the URL query. 
```json
{
  "milestone.title": {
    "$in": [
      "xxxxx"
    ]
  },
  "labels.edges": {
    "$elemMatch": {
      "node.name": {
        "$in": [
          "A"
        ]
      }
    },
    "$not": {
      "$elemMatch": {
        "node.name": {
          "$in": [
            "B"
          ]
        }
      }
    }
  }
}
```

The UI does not take the `$not` into account and having to write and maintain this for other issues is kind of difficulty. 

It would be nice if in the bar we have the option to select either include or exclude

**Comment by Fgerthoffert** [comment]
Hey @alexsapran,

I was playing with adding more complex facets filtering, but it quickly got pretty complex to get things to display properly (i.e. determine what to check or not in facets and keep some disjointed behavior). 

I don't think I'll be able to implement a `not` logic in the current version of ZenCrepes (lack of time). But I recently restarted to work on the ZenCrepes version backed-up by Elasticsearch (what I started back in June and had to put on hold). This feature could definitely be a good candidate for this upcoming update (not sure about a timeline).

Actually, there is something I might be able to add quickly (but let me know if that helps or not). The left side of the screen contains widgets, clicking on those widget generates a query composed of only issues IDs). If I add an "exclude label" or a toggle on the existing label widget, I should be able to easily generate a query of issues IDs excluding a selected label (i.e. label B). But doing that would mean you would lose the overall query context and will only be able to work with a dataset composed of the individual IDs.
Not sure if my explanations are clear or not :) I guess they are not :)

**Comment by Fgerthoffert** [comment]
Hey @alexsapran ,

I did something quickly, but I'm wondering if I ended up with a completely useless feature ;)

<img width="808" alt="Screen Shot 2020-02-08 at 3 39 34 PM" src="https://user-images.githubusercontent.com/5667028/74091783-6c874200-4a89-11ea-9a17-2a35e53182e8.png">

When enabling the switch, you can click on an element and the system will build an array of issues excluding the ones containing the element you clicked on. This is far from ideal, but it might be good enough for a short-term fix.

Can you give this a try, and let me know if that helps ?

It's available on https://dev.zencrepes.io/, you can play with it by adding issues from an organization such a `overture-stack`

Thanks,
Francois

**Comment by alexsapran** [comment]
Hi @Fgerthoffert I will give it a try but I am a bit full at this time, I will let you know when I have tried out.

Thanks for the prompt response.

**Comment by Fgerthoffert** [comment]
Hey @alexsapran,

I'm going to close this issue since the new version of ZenCrepes will (or does ;)) include a mechanism to edit the query, making it fairly simple to exclude labels (or any other field).

After giving it some thoughts, it's probably best to deal with those use through query edit versus trying to figure out a complex UI logic.

For example, all bugs except those assigned to you :)
<img width="1291" alt="Screen Shot 2020-08-26 at 7 58 03 PM" src="https://user-images.githubusercontent.com/5667028/91368220-7f1f5980-e7d6-11ea-967e-5298470bb853.png">
