### ISSUE TITLE
Cannot load /sprints

### ISSUE THREAD

**Issue by rosibaj** [zencrepes/zencrepes#73]
*Steps to reproduce* 
1. Go to prod zencrepes
2. Load fresh data from ICGC-ARGO and Overture Repos
3. Go to https://zencrepes.io/sprints 
--> the page will crash and is white
--> These console errors are seen 
<img width="1070" alt="Screen Shot 2019-04-22 at 3 21 57 PM" src="https://user-images.githubusercontent.com/15824252/56520526-a430f780-6512-11e9-90fd-e60f37363e00.png">
4. It looks like it is re-routing to https://zencrepes.io/sprints?q={%22title%22:{%22$in%22:[%22AACR%20Release%20&%20Maintainence%20KanBan%22]}} as the first sprint, but this sprint crashed the page for some reason

**Comment by Fgerthoffert** [comment]
ZenCrepes doesn't support special characters in the sprint title (and more generally in anything that gets translated into the URL by filtering).
In this particular occurrence `&`
Closing this ticket and creating one just for a feature.
